spring.datasource.url=jdbc:postgresql://localhost:5432/fidegresa_db
spring.datasource.username=postgres
spring.datasource.password=Manolo2004$
spring.datasource.driver-class-name=org.postgresql.Driver
